// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDapr9rrWv0bIL-VXkad6Mk2vQ7ozHPVQ',
    appId: '1:1021367726448:android:fcc5e6491a50e329ac1fb5',
    messagingSenderId: '1021367726448',
    projectId: 'single-salon-provider-f791a',
    storageBucket: 'single-salon-provider-f791a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu2MNsfzi-Q8rY9vm0ZPBviLT7W5T6CfQ',
    appId: '1:1021367726448:ios:c03ee0c779e58956ac1fb5',
    messagingSenderId: '1021367726448',
    projectId: 'single-salon-provider-f791a',
    storageBucket: 'single-salon-provider-f791a.appspot.com',
    androidClientId: '1021367726448-12f42v9rpc1mq14iue7b00u1ncv03o93.apps.googleusercontent.com',
    iosClientId: '1021367726448-dggjloc4md25g9u6puedrb9erh8htc1a.apps.googleusercontent.com',
    iosBundleId: 'com.example.salonApp',
  );
}
